### ISSUE TITLE
Data Bases Policies

### ISSUE THREAD

**Issue by paulosuzart** [ojkelly/bunjil#8]
Bunjil offers the hability add conditions to policies but conditions are tied only to the request context. That would be awesome if we could rely on returning data from upstream graphql to create more comprehensive conditions.

So where you have `field: "user.sessionAge",` (se wahn docs) youd could also do `$value.lastAccess` in this case the lookup value would happen agains the returned data for a resolver and not the context.

**Comment by ojkelly** [comment]
So you want to be able to make an authorization condition that matches against the result of the resolver?

This might not fit the way `wahn` is implemented. As the authorization call happens before the resolver is called -- this is especially important on mutations where it prevents data being changed without proper access.

In https://github.com/ojkelly/bunjil/blob/master/src/bunjil.ts#L224
```typescript            
const authorization: boolean = this.authorizationCallback({
  action,
  resource,
  context,
});
```

we are just passing in the whole resolver context object (so you can add additional stuff to that if you want to use it.

Do you have an example of a policy like this? It might help me understand how it would be possible.

**Comment by paulosuzart** [comment]
Hi @ojkelly thanks for the quick answer. We started building a proxy until we found bunjil and decided to switch over. But we were implementing the data based rules for query, but not mutations.

The idea is to cover situations like (imagine I'm writting a rule here):

`$data.userId == $context.usdId` for field `Employee::salary`

The idea is that if you have two authenticated users and a query like `getSalary(employeeId: Int!)`, using roles only won't prevent users to issue queries to `getSalary` with several different ids. 

So your front end might consume this query with the logged in user only, but accessing a browser developer console their can issue more queries and exploit breaches in the authorization scheme.

Of course this generates a dependency among fields. This way if a client issues a query like:

```
getSalary(employeeId: 21) {
   name
   # userId is not use instead injected by the proxy
}
```
and `Employee::name` also needs the rule above to be satisfied, the proxy  must include in the query the `userId` field, given that this field is required to process the rule. Of course the resulting data for `userId` must be removed before the payload is returned to the client.

Is it clearer now the situation we are trying to cover?

Regards

**Comment by ojkelly** [comment]
Yep that makes sense.

This is a use case for authn, that's very much on my mind and needs a solution. Solving it is tricky however.

To summarise the problem:
> We would like the capability to make a rule that can restrict access to a `Type` based on a comparison of the `context` (ie userId) and the returned information from the resolver (ie, userId on the `Post` type).

---

I think to make this work, I may need to move the authn check to after the resolver call for queries. Because we need to check for authn before processing a mutation. But challenge here, is that I can't enforce a specific order for resolver resolution, and I don't want to set a convention where say you need a `userId` edge on every type. So I'm not sure if this will work.

There may be an option to use schema directives here, to indicate a field that must be overwritten by the authentication hook.

So you would have a schema like:

```graphql

type Salary {
  id: ID!
  yearlyAmount: Number!
  userId: User @relation(name: "UserOnSalary") @overrideWithAuth(field: "context.user.id" )
}

```

That could possibly enforce the value for the edge will match the authenticated user.

I'm open to ideas for solving this, but I'll keep thinking to. This needs to be solved before I'd consider Bunjil production ready (which is the 1.1 milestone)

**Comment by ojkelly** [comment]
Another idea would be to have 2 authentication checks, one before and after the resolver.

**Comment by paulosuzart** [comment]
Your summary is accurate! 

Yes it would require rules to be processed after data is returned. But the lack of order for resolvers can lead to a situation where I want to compare data not yet loaded even if the rules are applied after the data is fetched.

A solution would be traverse the result object again after the query is fully resolved, this any data would be available.

All in all it seems to be something that can cause a considerable change in the way things work right now. Maybe it's better to go production ready as-is and consider such change if more people start to face situations like this.

Thanks for being open for the discussion. Regards

**Comment by ojkelly** [comment]
> Yes it would require rules to be processed after data is returned. But the lack of order for resolvers can lead to a situation where I want to compare data not yet loaded even if the rules are applied after the data is fetched.

This is the crux of it yeah.

> A solution would be traverse the result object again after the query is fully resolved, this any data would be available.

Yeah, this is how I came to thinking a secondary auth check could work, but it doesn't resolve the issue with mutations. ie, a user changing someone else's password.

> All in all it seems to be something that can cause a considerable change in the way things work right now. Maybe it's better to go production ready as-is and consider such change if more people start to face situations like this.

Possibly yeah, but I'd rather resolve it before there's a number of prod deploys. As it's in my opinion a massive security flaw waiting to happen, and my goal with Bunjil is to has secure defaults. Hopefully this wont take to long.

**Comment by paulosuzart** [comment]
So do you thing this data based rules approach should also be applied to mutations?

This would be possible to apply relatively easy to `variables` of a mutation, but if it depends on data stored in the upstream server I don't really know how to implement it in a easy way.

**Comment by ojkelly** [comment]
Schema Directives seem like a possible solution, where you can explicity say, everything on this field should be over-written by `context.user.userId`, to enforce the rule.

But I'm not that in favour, because it would mean a decent amount of effort on the dev's part to ensure the directives are on all the fields.

Best case would be being able to make a rule work, and as the authn policy check applies to everything by default, we should be able to make it work for `mutations` as well.

**Comment by ojkelly** [comment]
Another option I'm evaluating is the GraphQL Viewer pattern which might solve this.

**Comment by paulosuzart** [comment]
Let me see if I understood. Imagine I want to call `saveDraft(id: Int!, content: String!)` in a `Post` Type but it should be possible only if the current post, say `status`, is not `PUBLISHED`. So how to solve this given that at mutation time we don't have access to the post status bu only the variables/arguments?

I know it is plain old logic that should be handled by the server, but imagine prisma or alike where we don't have this kind of guard in the server side. I don't see how we could solve this without querying the post with whatever field is in the rules (`status` in this case) and then processing the rule before the mutation is sent.

**Comment by ojkelly** [comment]
So I've added the `root` and `args` objects from the resolver to the `context` object passed to `wahn`. And this works.

https://github.com/ojkelly/bunjil/blob/master/tests/integration/authorization.spec.ts#L428

```typescript
        {
            id: faker.random.uuid(),
            resources: ["User::*"],
            actions: ["query"],
            effect: PolicyEffect.Allow,
            roles: ["*"],
            conditions: [
                {
                    field: "user.userId",
                    operator: PolicyOperator.match,
                    expectedOnContext: ["root.id"],
                } as PolicyCondition,
            ],
        },
```

So that policy is saying you can only see a user, if the `User.id` matches the `user.userId` from the jwt.

I'm going to do a bit more reading into the execution of a GraphQL request to validate if this is actually going to work.

**Comment by ojkelly** [comment]
And based on this article, this is essentialy how Facebook do authz with the `viewer` pattern. By comparing a value on the root object, to a value from authn

https://dev-blog.apollodata.com/graphql-at-facebook-by-dan-schafer-38d65ef075af
